### PR TITLE
Front-end work 

### PR DESCRIPTION
**Pull request by Stevona**
Work done to connect api to Manage Customer, Add Customer and Edit Customer

Also updates on design for dashboard and couple other pages

Added login page

### CODE REVIEW

**Comment by Peter-Baker** [comment]
image

@Stevona I think you broke something sir!

**Review by pkgittjx22 — CHANGES_REQUESTED** [review]
Fix bug

**Comment by Stevona** [comment]
This Css is needed to make the background of the Dashboard the correct size, its valid css

**Review by Peter-Baker — APPROVED** [review]
It is time 😎

**Review by pkgittjx22 — APPROVED** [review]

**Pull request merged**
