### PR TITLE
Pubspec YAML change

### PR DESCRIPTION
**Pull request by mariaringes**

### CODE REVIEW

**Review by Peter-Baker — COMMENTED** [review]
@mariaringes Just want to make sure you meant to remove the following code: 

image

**Comment by mariaringes** [comment]
@alexmazzTJX Ideas?

**Review by Peter-Baker — APPROVED** [review]
Sounds good let's do it!

**Review by pkgittjx22 — APPROVED** [review]
Looks good

**Review by AmbiorisL — APPROVED** [review]

**Pull request merged**
